//POST https://phonebook-1-bzof.onrender.com/api/persons
//content-type: application/json

//{//    "name": "teav",
    //"number": "12345"
//}

GET 'https://mongodb+srv://aleksiasumalahti:PRRgNYExCK1HDikZ@fullstack.1qtys.mongodb.net/people?retryWrites=true&w=majority'